# Generated by Django 4.0.3 on 2022-05-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_products',
            field=models.FloatField(),
        ),
    ]
