# Generated by Django 4.0.3 on 2022-06-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0003_temperature_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=100)),
                ('Jan', models.FloatField(max_length=100)),
                ('Feb', models.FloatField(max_length=100)),
                ('Mar', models.FloatField(max_length=100)),
                ('Apr', models.FloatField(max_length=100)),
                ('May', models.FloatField(max_length=100)),
                ('Jun', models.FloatField(max_length=100)),
                ('Jul', models.FloatField(max_length=100)),
                ('Aug', models.FloatField(max_length=100)),
                ('Sep', models.FloatField(max_length=100)),
                ('Oct', models.FloatField(max_length=100)),
                ('Nov', models.FloatField(max_length=100)),
                ('Dec', models.FloatField(max_length=100)),
            ],
        ),
    ]
