# Generated by Django 4.0.3 on 2022-06-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0008_alter_monthlytemperature_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytemperature',
            name='year',
            field=models.IntegerField(),
        ),
    ]
