# Generated by Django 4.0.3 on 2022-06-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0012_alter_monthlytemperature_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytemperature',
            name='Jan',
            field=models.FloatField(verbose_name='JAN'),
        ),
    ]
