# Generated by Django 4.0.3 on 2022-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0013_alter_monthlytemperature_jan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytemperature',
            name='year',
            field=models.IntegerField(verbose_name='YEAR'),
        ),
    ]
