# Generated by Django 4.0.3 on 2022-06-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0017_rename_apr_monthlytemperature_apr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
